### ISSUE TITLE
Data processing

### ISSUE THREAD

**Issue by ChongminWang** [robotic-vision-lab/Learning-Implicitly-From-Spatial-Transformers-Network#1]
Hello, thank you for your work.
When I work with shapenet data，
parser.add_argument('--categories', nargs='+')
# shapenet for shapenet; # pix3d for pix3d
# parser.add_argument('--exp_name', type=str)
parser.add_argument('--file_path_glob', type=str, help='Path of the file from instance ID -> /<instance>*/*filename.ext')
I know what category to fill in，but I don't know what file_path_glob should fill in，can you tell me?
And, what are the parameters of pix3d?
Sorry, I am a newbie and I am looking forward to your reply!

**Comment by samiarshad** [comment]
Hi,

Thank you for your interest in our work.

The file path depends on the dataset you are using. For example, a typical Pix3D path is Pix3D/model/\<class\>/\<instance\>/model.obj. The 'file_path_glob' argument for such path would be 'Pix3D/model/\<class\> or \*/\*/model.obj'.

Hope it helps.

Best
