### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by SWWdz** [robotic-vision-lab/Learning-Implicitly-From-Spatial-Transformers-Network#5]
My training results are all the same among different category in shapenet dataset. Why? Can you tell me how to solve the problem? Thank you!

**Comment by samiarshad** [comment]
Hi, 

Thanks for your interest in our work. Could you please provide more information about your training procedure?

Did you train the coarse prediction module first? If not I would suggest training the coarse module first as the SDF prediction is affected heavily by the quality of coarse prediction.

Hope it helps.

**Comment by SWWdz** [comment]
I have do coarse_prediction to get point-cloud. And I see the result is ok. After that I use seperate.py to seperate the model. And when I train with LIST I find the test results are all the same in the different categories. Do you train model in all categories or one category for a model?
![image](https://github.com/robotic-vision-lab/Learning-Implicitly-From-Spatial-Transformers-Network/assets/104372768/05657287-8c13-4cd9-848b-b33dd7d9f53a)
