### ISSUE TITLE
This code is painful

### ISSUE THREAD

**Issue by A-cloud-bit** [robotic-vision-lab/Learning-Implicitly-From-Spatial-Transformers-Network#7]
Brothers, please don't do this code!!! The first stage memory is very high, according to the author's settings, the first stage 13GB and the second stage 24GB cannot run; Secondly, the code is extremely non compliant (although it may not be difficult to read, it is visible to the naked eye), with no environment or operation. To be honest, if you don't want to publish the code, you can choose not to publish it, rather than just perfunctory. Third: module splicing, which is also called innovation. Will the top quality be the only one. Reproducing your wasted day I use my own dataset, and even if your results are good, there is no desire for people to use it

**Comment by wjbeksi** [comment]
@A-cloud-bit this is not production code. I recommend reading the paper associated with this code to understand the resource requirements.
